name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]"

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: selenium/standalone-chrome:latest
      options: --user root  # Run as root user to avoid permission issues

    steps:
      - uses: actions/checkout@v4

      - name: Install Java 17 and Maven
        run: |
          apt-get update && \
          apt-get install -y openjdk-17-jdk maven && \
          apt-get clean

      - name: Pre-build Maven (Skip Tests)
        run: mvn clean install -DskipTests

      - name: Run Maven Tests
        run: mvn -q clean test

      - name: Archive HtmlReports
        uses: actions/upload-artifact@v3
        with:
          name: HtmlReports
          path: ./HtmlReports  # Specify the path to the HtmlReports folder

      - name: Archive Logs
        uses: actions/upload-artifact@v3
        with:
          name: Logs
          path: ./logs  # Specify the path to the logs folder
